from typing import Protocol


class AgentBootstrapPlugin(Protocol):
    plugin_id: str

    def supports(self, provider: dict, model: str) -> bool: ...

    def system_prompt(self) -> str: ...

    def tools(self) -> list[str]: ...

    def tool_definitions(self) -> list[dict]: ...

    def prepare(self) -> None: ...

    def call_tool(self, name: str, args: dict, context: dict): ...
