"""Shared product UI building blocks for the desktop application."""

from .primitives import (
    ProductActionBar,
    ProductCodeViewer,
    ProductDataRow,
    ProductEmptyState,
    ProductInlineNotice,
    ProductMasterDetail,
    ProductNavigationRow,
    ProductPageHeader,
    ProductSegmentedControl,
    ProductSection,
    ProductStatusBadge,
    ProductResultViewer,
    SidebarInlineNameEditor,
    ProductToolbar,
    apply_product_dialog,
    product_button_style,
    product_code_style,
    product_field_style,
    product_segmented_style,
    product_surface_style,
)

__all__ = [
    "ProductActionBar",
    "ProductCodeViewer",
    "ProductDataRow",
    "ProductEmptyState",
    "ProductInlineNotice",
    "ProductMasterDetail",
    "ProductNavigationRow",
    "ProductPageHeader",
    "ProductSegmentedControl",
    "ProductSection",
    "ProductStatusBadge",
    "ProductResultViewer",
    "SidebarInlineNameEditor",
    "ProductToolbar",
    "apply_product_dialog",
    "product_button_style",
    "product_code_style",
    "product_field_style",
    "product_segmented_style",
    "product_surface_style",
]
